// Generated by Wrangler by running `wrangler types`

interface Env {
	PUBLIC_REPOSITORIES: ["releases","snapshots"];
	PRIVATE_REPOSITORIES: ["private"];
	USERNAME: string;
	PASSWORD: string;
	VELA_BUCKET: R2Bucket;
}
