name = "vela"
main = "src/index.ts"
minify = true
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "vela.nguyenthanhtan.id.vn"
custom_domain = true

[vars]
PUBLIC_REPOSITORIES = ["releases", "snapshots"]
PRIVATE_REPOSITORIES = ["private"]

[[r2_buckets]]
binding = "VELA_BUCKET"
bucket_name = "vela"
preview_bucket_name = "vela-preview"
